import type { InventoryRow } from './types';

export const CONFIDENCE_BADGE_MAP = {
  high: 0.95,
  medium: 0.85,
  low: 0.6,
};

export const KNOWN_CANONICAL_COLUMNS: Array<InventoryRow & { description?: string }> = [
  {
    canonical_key: 'farm_name',
    label: 'Nome da Fazenda',
    category: 'identificacao',
    description: 'Identifica a fazenda de origem do registro.',
    synonyms: ['fazenda', 'propriedade', 'nome_fazenda', 'farm'],
  },
  {
    canonical_key: 'name',
    label: 'Nome do Animal',
    category: 'identificacao',
    description: 'Nome como o animal é conhecido na fazenda.',
    synonyms: ['nome', 'animal_nome', 'nome_animal'],
  },
  {
    canonical_key: 'identifier',
    label: 'Identificador',
    category: 'identificacao',
    description: 'Código/brinco único do animal na fazenda.',
    synonyms: ['animal', 'brinco', 'id_animal', 'identificacao', 'registro'],
  },
  {
    canonical_key: 'cdcb_id',
    label: 'ID CDCB',
    category: 'identificacao',
    description: 'Identificador do animal no CDCB.',
    synonyms: ['cdcb', 'id_cdcb', 'cdcbid'],
  },
  {
    canonical_key: 'category',
    label: 'Categoria',
    category: 'identificacao',
    description: 'Classificação da fêmea (doadora, receptora, etc).',
    synonyms: ['categoria_animal', 'classe', 'classificacao'],
  },
  {
    canonical_key: 'birth_date',
    label: 'Data de Nascimento',
    category: 'identificacao',
    description: 'Data de nascimento do animal.',
    synonyms: ['data_nascimento', 'nascimento', 'dt_nasc'],
  },
  {
    canonical_key: 'parity_order',
    label: 'Ordem de Parto',
    category: 'identificacao',
    description: 'Número da lactação/parto atual.',
    synonyms: ['ordem_parto', 'numero_parto', 'paridade'],
  },
  {
    canonical_key: 'sire_naab',
    label: 'Pai (NAAB)',
    category: 'identificacao',
    description: 'Código NAAB do pai.',
    synonyms: ['pai', 'pai_naab', 'sire'],
  },
  {
    canonical_key: 'mgs_naab',
    label: 'Avô Materno (NAAB)',
    category: 'identificacao',
    description: 'Código NAAB do avô materno.',
    synonyms: ['avo_materno', 'mgs'],
  },
  {
    canonical_key: 'mmgs_naab',
    label: 'Bisavô Materno (NAAB)',
    category: 'identificacao',
    description: 'Código NAAB do bisavô materno.',
    synonyms: ['bisavo_materno', 'mmgs'],
  },
  {
    canonical_key: 'hhp_dollar',
    label: 'HHP$',
    category: 'indice_economico',
    description: 'Health & Wellness Profit Dollar.',
    synonyms: ['hhp', 'hhp_dollar', 'health_dollar'],
  },
  {
    canonical_key: 'tpi',
    label: 'TPI',
    category: 'indice_economico',
    synonyms: ['tpi_index'],
  },
  {
    canonical_key: 'nm_dollar',
    label: 'NM$',
    category: 'indice_economico',
    description: 'Net Merit Dollar.',
    synonyms: ['nm', 'net_merit'],
  },
  {
    canonical_key: 'cm_dollar',
    label: 'CM$',
    category: 'indice_economico',
    description: 'Cheese Merit Dollar.',
    synonyms: ['cm', 'cheese_merit'],
  },
  {
    canonical_key: 'fm_dollar',
    label: 'FM$',
    category: 'indice_economico',
    description: 'Fluid Merit Dollar.',
    synonyms: ['fm', 'fluid_merit'],
  },
  {
    canonical_key: 'gm_dollar',
    label: 'GM$',
    category: 'indice_economico',
    description: 'Grazing Merit Dollar.',
    synonyms: ['gm', 'grazing_merit'],
  },
  {
    canonical_key: 'f_sav',
    label: 'Feed Saved',
    category: 'producao',
    synonyms: ['feed_saved', 'fsav'],
  },
  {
    canonical_key: 'ptam',
    label: 'PTA Milk',
    category: 'producao',
    synonyms: ['pta_milk', 'ptam'],
  },
  {
    canonical_key: 'cfp',
    label: 'CFP',
    category: 'producao',
    description: 'Cow Fertility Index.',
    synonyms: ['cow_fertility', 'cfp'],
  },
  {
    canonical_key: 'ptaf',
    label: 'PTA Fat',
    category: 'producao',
    synonyms: ['pta_fat', 'ptaf'],
  },
  {
    canonical_key: 'ptaf_pct',
    label: 'PTA Fat %',
    category: 'producao',
    synonyms: ['ptaf_percent', 'fat_pct'],
  },
  {
    canonical_key: 'ptap',
    label: 'PTA Protein',
    category: 'producao',
    synonyms: ['pta_protein', 'ptap'],
  },
  {
    canonical_key: 'ptap_pct',
    label: 'PTA Protein %',
    category: 'producao',
    synonyms: ['ptap_percent', 'protein_pct'],
  },
  {
    canonical_key: 'pl',
    label: 'Productive Life',
    category: 'producao',
    synonyms: ['productive_life', 'pl'],
  },
  {
    canonical_key: 'dpr',
    label: 'DPR',
    category: 'saude',
    description: 'Daughter Pregnancy Rate.',
    synonyms: ['dpr', 'daughter_pregnancy_rate'],
  },
  {
    canonical_key: 'liv',
    label: 'Livability',
    category: 'saude',
    synonyms: ['liv', 'livability'],
  },
  {
    canonical_key: 'scs',
    label: 'SCS',
    category: 'saude',
    description: 'Somatic Cell Score.',
    synonyms: ['somatic_cell_score', 'scs'],
  },
  {
    canonical_key: 'mast',
    label: 'Mastite',
    category: 'saude',
    synonyms: ['mastite', 'mastitis'],
  },
  {
    canonical_key: 'met',
    label: 'Metrite',
    category: 'saude',
    synonyms: ['metrite', 'met'],
  },
  {
    canonical_key: 'rp',
    label: 'Retained Placenta',
    category: 'saude',
    synonyms: ['retained_placenta', 'rp'],
  },
  {
    canonical_key: 'da',
    label: 'Deslocamento de Abomaso',
    category: 'saude',
    synonyms: ['deslocamento_abomaso', 'da'],
  },
  {
    canonical_key: 'ket',
    label: 'Cetose',
    category: 'saude',
    synonyms: ['cetose', 'ketosis'],
  },
  {
    canonical_key: 'mf',
    label: 'Milking Speed',
    category: 'saude',
    synonyms: ['milking_speed', 'mf'],
  },
  {
    canonical_key: 'ptat',
    label: 'PTA Type',
    category: 'conformacao',
    synonyms: ['pta_type', 'ptat'],
  },
  {
    canonical_key: 'udc',
    label: 'Udder Composite',
    category: 'conformacao',
    synonyms: ['udder_composite', 'udc'],
  },
  {
    canonical_key: 'flc',
    label: 'Feet & Legs Composite',
    category: 'conformacao',
    synonyms: ['feet_legs_composite', 'flc'],
  },
  {
    canonical_key: 'sce',
    label: 'Sire Calving Ease',
    category: 'conformacao',
    synonyms: ['sire_calving_ease', 'sce'],
  },
  {
    canonical_key: 'dce',
    label: 'Daughter Calving Ease',
    category: 'conformacao',
    synonyms: ['daughter_calving_ease', 'dce'],
  },
  {
    canonical_key: 'ssb',
    label: 'Sire Stillbirth',
    category: 'conformacao',
    synonyms: ['sire_stillbirth', 'ssb'],
  },
  {
    canonical_key: 'dsb',
    label: 'Daughter Stillbirth',
    category: 'conformacao',
    synonyms: ['daughter_stillbirth', 'dsb'],
  },
  {
    canonical_key: 'h_liv',
    label: 'Heifer Livability',
    category: 'conformacao',
    synonyms: ['heifer_livability', 'h_liv'],
  },
  {
    canonical_key: 'ccr',
    label: 'Cow Conception Rate',
    category: 'conformacao',
    synonyms: ['cow_conception_rate', 'ccr'],
  },
  {
    canonical_key: 'hcr',
    label: 'Heifer Conception Rate',
    category: 'conformacao',
    synonyms: ['heifer_conception_rate', 'hcr'],
  },
  {
    canonical_key: 'fi',
    label: 'Fertility Index',
    category: 'conformacao',
    synonyms: ['fertility_index', 'fi'],
  },
  {
    canonical_key: 'gl',
    label: 'Gestation Length',
    category: 'conformacao',
    synonyms: ['gestation_length', 'gl'],
  },
  {
    canonical_key: 'efc',
    label: 'Early First Calving',
    category: 'conformacao',
    synonyms: ['early_first_calving', 'efc'],
  },
  {
    canonical_key: 'bwc',
    label: 'Body Weight Composite',
    category: 'conformacao',
    synonyms: ['body_weight_composite', 'bwc'],
  },
  {
    canonical_key: 'sta',
    label: 'Strength',
    category: 'conformacao',
    synonyms: ['strength', 'sta'],
  },
  {
    canonical_key: 'str',
    label: 'Stature',
    category: 'conformacao',
    synonyms: ['stature', 'str'],
  },
  {
    canonical_key: 'dfm',
    label: 'Dairy Form',
    category: 'conformacao',
    synonyms: ['dairy_form', 'dfm'],
  },
  {
    canonical_key: 'rua',
    label: 'Rump Width',
    category: 'conformacao',
    synonyms: ['rump_width', 'rua'],
  },
  {
    canonical_key: 'rls',
    label: 'Rear Legs Side View',
    category: 'conformacao',
    synonyms: ['rear_legs_side', 'rls'],
  },
  {
    canonical_key: 'rtp',
    label: 'Rump Angle',
    category: 'conformacao',
    synonyms: ['rump_angle', 'rtp'],
  },
  {
    canonical_key: 'ftl',
    label: 'Front Teat Length',
    category: 'conformacao',
    synonyms: ['front_teat_length', 'ftl'],
  },
  {
    canonical_key: 'rw',
    label: 'Rear Width',
    category: 'conformacao',
    synonyms: ['rear_width', 'rw'],
  },
  {
    canonical_key: 'rlr',
    label: 'Rear Legs Rear View',
    category: 'conformacao',
    synonyms: ['rear_legs_rear', 'rlr'],
  },
  {
    canonical_key: 'fta',
    label: 'Front Teat Placement',
    category: 'conformacao',
    synonyms: ['front_teat_placement', 'fta'],
  },
  {
    canonical_key: 'fls',
    label: 'Foot & Leg Score',
    category: 'conformacao',
    synonyms: ['foot_leg_score', 'fls'],
  },
  {
    canonical_key: 'fua',
    label: 'Final Score',
    category: 'conformacao',
    synonyms: ['final_score', 'fua'],
  },
  {
    canonical_key: 'ruh',
    label: 'Rear Udder Height',
    category: 'conformacao',
    synonyms: ['rear_udder_height', 'ruh'],
  },
  {
    canonical_key: 'ruw',
    label: 'Rear Udder Width',
    category: 'conformacao',
    synonyms: ['rear_udder_width', 'ruw'],
  },
  {
    canonical_key: 'ucl',
    label: 'Udder Cleft',
    category: 'conformacao',
    synonyms: ['udder_cleft', 'ucl'],
  },
  {
    canonical_key: 'udp',
    label: 'Udder Depth',
    category: 'conformacao',
    synonyms: ['udder_depth', 'udp'],
  },
  {
    canonical_key: 'ftp',
    label: 'Foot Angle',
    category: 'conformacao',
    synonyms: ['foot_angle', 'ftp'],
  },
  {
    canonical_key: 'rfi',
    label: 'Rear Foot Index',
    category: 'conformacao',
    synonyms: ['rear_foot_index', 'rfi'],
  },
  {
    canonical_key: 'gfi',
    label: 'General Feet Index',
    category: 'conformacao',
    synonyms: ['general_feet_index', 'gfi'],
  },
  {
    canonical_key: 'kappa_casein',
    label: 'Kappa Caseína',
    category: 'variantes',
    synonyms: ['kappa_caseina', 'kappa_casein'],
  },
  {
    canonical_key: 'beta_casein',
    label: 'Beta Caseína',
    category: 'variantes',
    synonyms: ['beta_caseina', 'beta_casein'],
  },
  {
    canonical_key: 'last_prediction_method',
    label: 'Método da Última Predição',
    category: 'predicoes',
    synonyms: ['metodo_predicao', 'ultima_predicao_metodo'],
  },
  {
    canonical_key: 'last_prediction_value',
    label: 'Valor da Última Predição',
    category: 'predicoes',
    synonyms: ['valor_predicao', 'ultima_predicao_valor'],
  },
  {
    canonical_key: 'last_prediction_confidence',
    label: 'Confiança da Última Predição',
    category: 'predicoes',
    synonyms: ['confianca_predicao', 'ultima_predicao_confianca'],
  },
  {
    canonical_key: 'last_prediction_date',
    label: 'Data da Última Predição',
    category: 'predicoes',
    synonyms: ['data_predicao', 'ultima_predicao_data'],
  },
  {
    canonical_key: 'segmentation_class',
    label: 'Classe de Segmentação',
    category: 'segmentacao',
    synonyms: ['classe_segmentacao', 'segmentacao'],
  },
  {
    canonical_key: 'segmentation_score',
    label: 'Score de Segmentação',
    category: 'segmentacao',
    synonyms: ['score_segmentacao', 'segmentacao_score'],
  },
];

export const STANDARD_OUTPUT_HEADERS = KNOWN_CANONICAL_COLUMNS.map((column) => column.canonical_key);

export const REQUIRED_CANONICAL_KEYS = ['farm_name', 'name', 'identifier'];
