import type { CanonicalColumn } from './types';

export const KNOWN_CANONICAL_COLUMNS: CanonicalColumn[] = [
  {
    canonical_key: 'parity_order',
    label_pt: 'Ordem de Parto',
    label_en: 'Parity Order',
    datatype: 'number',
    category: 'meta',
    required: true,
  },
  {
    canonical_key: 'category',
    label_pt: 'Categoria',
    label_en: 'Category',
    datatype: 'string',
    category: 'meta',
    required: true,
  },
  {
    canonical_key: 'id',
    label_pt: 'Identificador Interno',
    label_en: 'ID',
    datatype: 'string',
    category: 'meta',
    required: true,
  },
  {
    canonical_key: 'farm_id',
    label_pt: 'Fazenda ID',
    label_en: 'Farm ID',
    datatype: 'string',
    category: 'meta',
    required: true,
  },
  {
    canonical_key: 'name',
    label_pt: 'Nome',
    label_en: 'Name',
    datatype: 'string',
    category: 'meta',
    required: true,
  },
  {
    canonical_key: 'identifier',
    label_pt: 'Identificador',
    label_en: 'Identifier',
    datatype: 'string',
    category: 'meta',
    required: true,
  },
  {
    canonical_key: 'cdcb_id',
    label_pt: 'CDCB ID',
    label_en: 'CDCB ID',
    datatype: 'string',
    category: 'meta',
    required: true,
  },
  {
    canonical_key: 'mgs_naab',
    label_pt: 'MGS NAAB',
    label_en: 'MGS NAAB',
    datatype: 'string',
    category: 'meta',
    required: true,
  },
  {
    canonical_key: 'mmgs_naab',
    label_pt: 'MMGS NAAB',
    label_en: 'MMGS NAAB',
    datatype: 'string',
    category: 'meta',
    required: true,
  },
  {
    canonical_key: 'birth_date',
    label_pt: 'Data de Nascimento',
    label_en: 'Birth Date',
    datatype: 'date',
    category: 'meta',
    required: true,
  },
  {
    canonical_key: 'ptas',
    label_pt: 'PTAs',
    label_en: 'PTAs',
    datatype: 'string',
    category: 'PTA',
    required: true,
  },
  {
    canonical_key: 'created_at',
    label_pt: 'Criado em',
    label_en: 'Created At',
    datatype: 'date',
    category: 'meta',
    required: true,
  },
  {
    canonical_key: 'updated_at',
    label_pt: 'Atualizado em',
    label_en: 'Updated At',
    datatype: 'date',
    category: 'meta',
    required: true,
  },
  {
    canonical_key: 'sire_naab',
    label_pt: 'Pai (NAAB)',
    label_en: 'Sire NAAB',
    datatype: 'string',
    category: 'meta',
    required: true,
  },
  { canonical_key: 'nm_dollar', label_pt: 'NM$', label_en: 'Net Merit', datatype: 'number', category: 'indice' },
  { canonical_key: 'hhp_dollar', label_pt: 'HHP$', label_en: 'Herd Health Profit', datatype: 'number', category: 'indice' },
  { canonical_key: 'tpi', label_pt: 'TPI', label_en: 'Total Performance Index', datatype: 'number', category: 'indice' },
  { canonical_key: 'ptam', label_pt: 'PTAM', label_en: 'PTA Milk', datatype: 'number', category: 'PTA', unit: 'lb' },
  {
    canonical_key: 'ptaf_percent',
    label_pt: 'PTAF%',
    label_en: 'PTA Fat %',
    datatype: 'percent',
    category: 'PTA',
    unit: '%',
  },
  {
    canonical_key: 'ptap_percent',
    label_pt: 'PTAP%',
    label_en: 'PTA Protein %',
    datatype: 'percent',
    category: 'PTA',
    unit: '%',
  },
  { canonical_key: 'scs', label_pt: 'SCS', label_en: 'Somatic Cell Score', datatype: 'number', category: 'indice' },
  {
    canonical_key: 'dpr',
    label_pt: 'DPR',
    label_en: 'Daughter Pregnancy Rate',
    datatype: 'percent',
    category: 'meta',
    unit: '%',
  },
];

export const REQUIRED_CANONICAL_KEYS = KNOWN_CANONICAL_COLUMNS.filter((column) => column.required).map(
  (column) => column.canonical_key,
);

export const CONFIDENCE_BADGE_MAP = {
  high: 0.95,
  medium: 0.88,
};
