
-- Importação completa de todos os vínculos técnicos-fazendas

CREATE TEMP TABLE temp_all_technician_links (
  owner_name TEXT,
  farm_name TEXT,
  technician_name TEXT
);

-- Inserir TODOS os 347 registros do CSV
INSERT INTO temp_all_technician_links (owner_name, farm_name, technician_name) VALUES
('CLAUDIO E SEMILDO SCHIEFELBEIN', 'Fazenda', 'Bruna Schiefelbein'),
('HANS GROENWOLD', 'Fazenda Fini', 'Bruna Schiefelbein'),
('IRMÃOS STROBEL', 'FAZENDA SANTA ISABEL', 'Bruna Schiefelbein'),
('FELIPE DE JAGER', 'FAZENDA OURO VERDE', 'Bruna Schiefelbein'),
('Select Sires', 'Fazenda SS', 'Bruna Schiefelbein'),
('ELEANDRO ARSEGO', 'FAZENDA ARSEGO', 'Bruna Schiefelbein'),
('CARLOS JACOB WALLAUER', 'FAZENDA FORTALEZA', 'Bruna Schiefelbein'),
('TIAGO HUBER', 'TIAGO HUBER', 'Bruna Schiefelbein'),
('FAZENDA SAN DIEGO', 'SAN DIEGO', 'Bruna Schiefelbein'),
('JONATHAN ORSOLIN', 'JONATHAN ORSOLINN', 'Bruna Schiefelbein'),
('GRANJAS 4 IRMÃOS', 'GRANJAS 4 IRMÃOS', 'Bruna Schiefelbein'),
('PAULO MOSS', 'AGROPECUÁRIA MOSS', 'Bruna Schiefelbein'),
('FAZENDA MAMANGAVA- REBANHO FINI', 'FAZENDA MAMANGAVA', 'Bruna Schiefelbein'),
('IRMÃOS CERUTTI', 'IRMAOS CERUTTI', 'Bruna Schiefelbein'),
('Fazenda demonstrativa', 'Fazenda demonstrativa', 'Bruna Schiefelbein'),
('GRANJA MARIVO', 'GRANJA MARIVO', 'Bruna Schiefelbein'),
('FRITZ SEARA', 'FRITZ SEARA', 'Bruna Schiefelbein'),
('INGOLF SPECHT', 'IRMÃOS SPECHT', 'Bruna Schiefelbein'),
('GREGORY TEDESCO', 'TAMBO TEDESCO', 'Bruna Schiefelbein'),
('Jairo Gempka', 'FAZENDA JG', 'Bruna Schiefelbein'),
('Rodrigo Spoonchiado', 'Fazenda Sponchiado', 'Bruna Schiefelbein'),
('ANTONIO BRAZ TINOCO', 'ARTAGRO', 'Bruna Schiefelbein'),
('Edson Ferreira Rocha', 'Fazenda', 'Bruna Schiefelbein'),
('Rodolfo Bordignhon', 'Fazenda Bordinhon', 'Bruna Schiefelbein'),
('Julio Vieira', 'FAZENDA SANTA ELMIRA', 'Bruna Schiefelbein'),
('Lucio Drinko', 'Lucio Drinko', 'Bruna Schiefelbein'),
('RICHARD VERBURG', 'RICHARD VERBURG', 'Bruna Schiefelbein'),
('Larissa', 'UTFPR', 'Larissa Cunha'),
('JOSÉ OSVALDO NUNES', 'FAZENDA ESPERANÇA', 'Diego Marcondes Guerra'),
('DANIEL ANDRE DA SILVA', 'FAZENDA BRAVINHOS', 'Diego Marcondes Guerra'),
('SILVIO GERALDO MARTINS', 'FAZENDA PASTO DO BOIS', 'Diego Marcondes Guerra'),
('CARLOS FERNANDO MOREIRA DA CUNHA', 'FAZENDA PARAISO', 'Diego Marcondes Guerra'),
('DIMAS DE DEUS VIEIRA E OUTROS', 'FAZENDA BABILONIA', 'Diego Marcondes Guerra'),
('OSMAR MARRA DE OLIVEIRA', 'FAZENDA FIGUEIREDO', 'Diego Marcondes Guerra'),
('CELSO ANTONIO ROSA E OUTROS', 'FAZENDA FORTALEZA', 'Diego Marcondes Guerra'),
('GILSON PEREIRA CARDOSO', 'FAZENDA ALAGOAS', 'Diego Marcondes Guerra'),
('SILMAR GERALDO MARTINS', 'FAZENDA BATATAL', 'Diego Marcondes Guerra'),
('EDGAR MOREIRA GUIMARAES', 'FAZENDA BARREIRA', 'Diego Marcondes Guerra'),
('CAROLINE SEIBT E OUTROS', 'CONDOMINIO FAZENDA GAUCHA', 'Diego Marcondes Guerra'),
('VALTER JOSE DE SANTANA', 'FAZENDA BABILONIA', 'Diego Marcondes Guerra'),
('ANTONIO JOSE FREIRE', 'FAZENDA PÉROLA', 'Diego Marcondes Guerra'),
('ODAIR ANTONIO CENCI', 'FAZENDA CENCI', 'Diego Marcondes Guerra'),
('Jacques Gontijo Alvares (Doadoras)', 'Jacques Gontijo Alvares', 'Diego Marcondes Guerra'),
('Jacques Gontijo Alvares (Todo)', 'Jacques Gontijo Alvares', 'Diego Marcondes Guerra'),
('ClickWeb', 'Fazenda ClickWeb', 'Diego Marcondes Guerra'),
('Teste Lucas', 'Clickweb', 'Diego Marcondes Guerra'),
('José Guilherme Vasconcelos', 'Fazenda Santa Izabel', 'Diego Marcondes Guerra'),
('Teste Gustavo', 'Teste', 'Luis Gustavo C Figueiredo'),
('DANIEL MOREIRA', 'CACAPAVA', 'Daniel Moreira'),
('RODRIGO MOTTER TAFFAREL', 'AGROPECUÁRIA TAFFAREL', 'Daniel Moreira'),
('NILVA TEREZINHA RANDON', 'RAR', 'Daniel Moreira'),
('VILIBALDO E. SCHIMIDT', 'FAZENDA', 'Daniel Moreira'),
('JOAO MARCOS DINIZ', 'FAZENDA DINIZ', 'Daniel Moreira'),
('Fernando Raul de Boer', 'Fazenda do Boer', 'MIchael Warkentin'),
('Geraldo Tomazi', 'Granja Tomazi', 'MIchael Warkentin'),
('Paulo Doering', 'Fazenda Douwe', 'MIchael Warkentin'),
('Christian Kliewer', 'AgroKonquista', 'MIchael Warkentin'),
('MANFRED DÜCK', 'AGROPECUÁRIA OURO BRANCO', 'MIchael Warkentin'),
('Canto Porto', 'Canto Portp', 'MIchael Warkentin'),
('AGROPECUARIA FAZENDA OURO BRANCO', 'FAZENDA OURO BRANCO', 'MIchael Warkentin'),
('DANIEL ROEPKE', 'FAZENDA SHANGRILA', 'MIchael Warkentin'),
('CARLOS RICKLI', 'RICKLI', 'MIchael Warkentin'),
('LÉO PAULO BARTH', 'LÉO PAULO BARTH', 'MIchael Warkentin'),
('Roberto Ari de Castro Greidanus', 'Fazenda Rincão', 'MIchael Warkentin'),
('JOÃO SANTI', 'SANTANNA', 'MIchael Warkentin'),
('Rafael Baldissera', 'Rafael Baldissera', 'MIchael Warkentin'),
('Melkstad', 'Fazenda', 'MIchael Warkentin'),
('JOSE ERAMILDO GARCIA ABICH', 'SITIO NOSSA SENHORA', 'MARIANA NASI'),
('Cezar Rossato', 'Fazenda Rossato', 'MARIANA NASI'),
('GERALDO OTT', 'GRANJA ESPLANADA', 'MARIANA NASI'),
('Valdir Schwantes', 'AGROPECUARIA PUXIRETÊ', 'MARIANA NASI'),
('FERNANDO DALZOTTO', 'FAZENDA DALZOTTO', 'MARIANA NASI'),
('JEFERSON KIRSTEN', 'FAZENDA KIRSTEN', 'MARIANA NASI'),
('INELSON FIOREZE', 'FAZENDA PINHEIRINHO', 'MARIANA NASI'),
('EDIOVANE DELA JUSTINA', 'fazenda dela justia', 'MARIANA NASI'),
('Gerson Neumann', 'Granja Neumann', 'MARIANA NASI'),
('DIEGO CORAZZA', 'CORAZZA FARM', 'MARIANA NASI'),
('FAZ TESTE', 'TESTE AGROP', 'MARIANA NASI'),
('DOUGLAS ALENCAR GOIN', 'AGROP GOIN', 'MARIANA NASI'),
('ANDRE HEPP', 'AGROPECUARIA VALE VERDE', 'MARIANA NASI'),
('VALTER GHISSI', 'FAZENDA GHISSI', 'MARIANA NASI'),
('LUAN BUENO', 'TAMBO BELA VISTA', 'MARIANA NASI'),
('RODRIGO SINSKI', 'SINSKI', 'MARIANA NASI'),
('ISMAEL BECKER', 'BEKER', 'MARIANA NASI'),
('ADILSON PAHOHECK', 'PAHOHECK', 'MARIANA NASI'),
('SAMUEL ROSSI', 'FAZENDA ROSSI', 'MARIANA NASI'),
('LUCIANO CERON', 'Luciano Pelentir Ceron', 'MARIANA NASI'),
('IVANIR RIGON', 'FAZ RIGON', 'MARIANA NASI'),
('ARNO THALLER', 'LEITARIA TIROLESA', 'MARIANA NASI'),
('PEDRO PAULO COLLETT', 'FAZ COLLETT', 'MARIANA NASI'),
('RONI MEZZALIRA', 'FAZENDA MEZZALIRA', 'MARIANA NASI'),
('LIDIANE MENEGOL', 'AGROP MENEGOL', 'MARIANA NASI'),
('LUCAS PALUDO', 'LUCAS PALUDO', 'MARIANA NASI'),
('OLENI MOCELIN', 'OLENI MOCELIN', 'MARIANA NASI'),
('GABRIELA DEGASPERI', 'GRANJA DEGASPERI', 'MARIANA NASI'),
('ROBERTO FINGER', 'FAZENDA FINGER', 'MARIANA NASI'),
('ABILIO KLASENER', 'FAZ KLASENER', 'MARIANA NASI'),
('CASSIANO ARIEL MENSCH', 'FAZ MENSCH', 'MARIANA NASI'),
('JHONATAN ORSOLIN', 'GRANJA ORSOLIN', 'MARIANA NASI'),
('FRANCISCO BANDEIRA', 'AGROPECUARIA BANDEIRA', 'MARIANA NASI'),
('JHONATAN ORSOLIN', 'GRANJA ORSOLIN', 'MARIANA NASI'),
('STEFAN RICHTER', 'AGRO RICHTER', 'MARIANA NASI'),
('ALEX BERWIG', 'AGROPECUARIA BERWIG', 'MARIANA NASI'),
('LUCIANO PORAZZI', 'Fazenda Porazzi', 'MARIANA NASI'),
('DAVI GASS', 'FAZENDA GASS', 'MARIANA NASI'),
('AGROPECUARIA ARAPARI', 'AGROPECUARIA ARAPARI', 'MARIANA NASI'),
('GEDIEL GREIBELER', 'FAZ GREIBELER', 'MARIANA NASI'),
('GABRIELA PUTTON', 'AMORE PER LE MUCCHE', 'MARIANA NASI'),
('Gabriele Gentarski', 'Gabriele Gentarski', 'MARIANA NASI'),
('PALMA', 'PALMA AGROPECUÁRIA', 'Manuela Gama'),
('FAZENDA DEMO', 'FAZENDA DEMONSTRATIVO', 'Manuela Gama'),
('André Nogueira Junqueira', 'Fazenda Cativo', 'André Junqueira'),
('Carlos Ribeiro', 'Fazenda Santa Cruz', 'Carlos Augusto'),
('Bolivar de Melo Ribeiro', 'Demo', 'Carlos Augusto'),
('Marcos Paiva Frota', 'Fazenda Baixadão', 'Carlos Augusto'),
('JOSÉ HUMBERTO GARCIA JÚNIOR', 'FAZENDA VALE DO SÃO JOÃO', 'Carlos Augusto'),
('SILVANO CARVALHO', 'FAZ SAO JOSE', 'Silvano Carvalho'),
('JOSE GONÇALVES', 'NOSSA SENHORA', 'Silvano Carvalho'),
('FABIANA SOARES FERREIRA', 'FAZENDA VARJAO', 'Silvano Carvalho'),
('JACQUES GONTIJO ALVARES', 'FAZENDA SÃO PEDRO', 'Silvano Carvalho'),
('SIGRID DE CASTRO FONSECA', 'FAZENDA TROLE', 'Silvano Carvalho'),
('CELSO ANTONIO ROSA', 'FAZENDA FORTALEZA', 'Silvano Carvalho'),
('BIRA E MUCA - GENÔMICO', 'FAZ. CAJUEIRO', 'Silvano Carvalho'),
('BIRA E MUCA- PREDIÇÃO', 'FAZ. CAJUEIRO', 'Silvano Carvalho'),
('FABIO GUIMARAES PEREIRA', 'FAZENDA CANADA', 'Silvano Carvalho'),
('JOSE ANTONIO LOPES DE OLIVEIRA', 'FAZ. SAGUATIBA', 'Silvano Carvalho'),
('EDER PIMENTA', 'EDER', 'Silvano Carvalho'),
('FRANCISCO OTAVIANO FONSECA OLIVEIRA', 'FAZENDA MATO GROSSO', 'Silvano Carvalho'),
('BRUNA LUIZA DE MATOS SILVAA', 'FAZ CHAPADAO DAS GUARITAS', 'Silvano Carvalho'),
('RAFAEL COELHO DE QUEIROZ E OUTORS', 'FAZENDA VARGEM FRIA', 'Silvano Carvalho'),
('ADELIO DA FONSECA', 'FAZENDA LAGEADO', 'Silvano Carvalho'),
('CELSO CARLOS DE OLIVEIRA', 'FAZENDA CELSO CARLOS', 'Silvano Carvalho'),
('JULIO CELIO OLIVEIRA VARGAS', 'FAZENDA JULIO CELIO', 'Silvano Carvalho'),
('ILZA DOS REIS MATOS', 'FAZENDA SANTO ANTONIO', 'Silvano Carvalho'),
('PEDRO PAULO DE REZENDE', 'FAZENDA SERTAO', 'Silvano Carvalho'),
('WILIAM DOS REIS PEREIRA', 'FAZENDA SERRA NEGRA', 'Silvano Carvalho'),
('ANTONIO JOSE FREIRE', 'FAZENDA PEROLA', 'Silvano Carvalho'),
('ILDEU JOSE ASSUNCAO', 'FAZENDA ILDEU', 'Silvano Carvalho'),
('AGROPECUARIA FASAQUI', 'FASAQUI', 'Silvano Carvalho'),
('FASAQUI NXGEN', 'FASAQUI', 'Silvano Carvalho'),
('ALENCAR FRANCISCO PERERIA', 'FAZANDA ALENCAR', 'Silvano Carvalho'),
('PAULO DIAS DE SOUSA', 'FAZENDA PAULO', 'Silvano Carvalho'),
('NILSON GONZAGA COELHO', 'FAZENDA NILSON', 'Silvano Carvalho'),
('DANIEL SOARES AMARAL', 'FAZENDA CHAPADAO', 'Silvano Carvalho'),
('MARIA ADRIANA SOUZA DE DEUS CUNHA', 'FAZENDA BRAVINHOS', 'Silvano Carvalho'),
('PEDRO EULLER MARTINS', 'FAZENDA UNIAO', 'Silvano Carvalho'),
('GESO DA MOTA LIMA', 'FAZENDA GESO', 'Silvano Carvalho'),
('BARTOLOMEU FERNANDES DE LIMA', 'AGROPECUARIA FERNANDES', 'Silvano Carvalho'),
('LUIZ ALEXANDRE DE AVELAR', 'FAZ CAMPO ALEGRE', 'Silvano Carvalho'),
('AGRONELLI AGROINDUSTRIA', 'FAZENDA AGRONELLI', 'Silvano Carvalho'),
('JOSE LUIZ SOARES', 'FAZENDA JOSE LUIZ', 'Silvano Carvalho'),
('WILSON DONIZETTI DA SILVA', 'FAZ. WILSON', 'Silvano Carvalho'),
('PAULO CEZAR SILVA MELO', 'FAZ MATINHA DAS PITAS', 'Silvano Carvalho'),
('CAROLINE SEIBT', 'FAZ TRES PONTAS', 'Silvano Carvalho'),
('HORACIO JOSE FERREIRA', 'FAZENDA MACAUBA', 'Silvano Carvalho'),
('PAULO DIAS DE SOUZA', 'FAZ ALAGOAS', 'Silvano Carvalho'),
('RONALDO MOREIRA SOARES', 'FAZENDA CHAPADAO', 'Silvano Carvalho'),
('Valtonio Soares', 'FAZ VALTONIO', 'Silvano Carvalho'),
('MATEUS SOUZA CORREA', 'FAZENDA MATEUS', 'Silvano Carvalho'),
('ANTONIO JOSE MARQUES', 'FAZENDA', 'Silvano Carvalho'),
('PAULO CEZAR DE AVILA', 'FAZENDA', 'Silvano Carvalho'),
('JOSE ALVES DA SILVA', 'FAZENDA', 'Silvano Carvalho'),
('JOSE MARIA BRAGA', 'FAZENDA', 'Silvano Carvalho'),
('SILVIO GERALDO MARTINS', 'FAZENDA PASTO DOS BOIS', 'Silvano Carvalho'),
('MARCIO DA ROCHA LIMA JUNIOR', 'FAZ PARAIZO SANTA HELENA', 'Silvano Carvalho'),
('SERGIO LUIZ', 'FAZ PUEIRAO', 'Silvano Carvalho'),
('TIAGO ALVES MOREIRA', 'FAZENDA ALVES', 'Silvano Carvalho'),
('FELIPE GUSTAVO BAETA E OUTROS', 'FAZENDA BELA VISTA', 'Silvano Carvalho'),
('OSMAR ALVES BRAGA', 'FAZENDA OSMAR', 'Silvano Carvalho'),
('GESO DA MOTA LIMA', 'FAZENDA BAU', 'Silvano Carvalho'),
('CARLOS ALBERTO MENDES', 'FAZENDA CARLOS ALBERTO', 'Silvano Carvalho'),
('DIMAS GONZAGA', 'FAZENDA BOA VISTA', 'Silvano Carvalho'),
('RENATO NUNES', 'FAZENDA PARIPITINGA', 'Silvano Carvalho'),
('JAIDER SHIMADA', 'FAZENDA JAIDER', 'Silvano Carvalho'),
('ANTONIO EUSTAQUIO FERNANDES', 'FAZENDA CABECEIRA MONJOLINHO', 'Silvano Carvalho'),
('PAULO SERGIO NOGUEIRA', 'FAZ.', 'Silvano Carvalho'),
('CLEBER SIQUEIRA DINIZ', 'FAZENDA CLEBER', 'Silvano Carvalho'),
('FAZENDA LANHOSOS-NEGO', 'LANHOSOS', 'Silvano Carvalho'),
('WANDERSON MENDES ROCHA', 'FAZENDA WANDERSON', 'Silvano Carvalho'),
('LUIZ VINICIUS DE CASTRO RANGEL', 'FAZENDA RANGEL', 'Silvano Carvalho'),
('ANTONIO CESAR MANI', 'FAZENDA MANI', 'Silvano Carvalho'),
('WELLINGTON DOUGLAS SOUZA SILVA', 'FAZENDA PANORAMA', 'Silvano Carvalho'),
('ARI BELMIRO', 'FAZENDA BELMIRO', 'Silvano Carvalho'),
('ROBERTO ARAUJO CAMPOS', 'FAZ ROBERTO', 'Silvano Carvalho'),
('Thiago Castro', 'Faz Canaã', 'Thiago Castro'),
('Claudio Junqueira', 'Grupo JFA', 'Thiago Castro'),
('Gabriely', 'Select', 'Gabriely Pinheiro'),
('DEMONSTRATIVA', 'FAZENDA', 'Gabriely Pinheiro'),
('ANTONIO JOSE FREIRE', 'FAZENDA PEROLA', 'Gabriely Pinheiro'),
('VITOR PENIDO DE BARROS', 'FAZENDA PONTE ALTA PAU DO MONJOLO', 'Gabriely Pinheiro'),
('GUSTAVO FREITAS ILHA', 'FAZENDA FINI', 'Gustavo Ilha'),
('Júlio André de Oliveira - Renascence', 'Fazenda Renascence', 'LUIZ OLIVEIRA'),
('Júlio André de Oliveira - TDL', 'Fazenda Terra do Leite', 'LUIZ OLIVEIRA'),
('Júlio André de Oliveira - Morro Vermelho', 'Fazenda Morro Vermelho', 'LUIZ OLIVEIRA'),
('Júlio André de Oliveira - Santo Antônio', 'Fazenda Santo Antônio', 'LUIZ OLIVEIRA'),
('Júlio André de Oliveira - Três Lagoas', 'Fazenda Três Lagoas', 'LUIZ OLIVEIRA'),
('TESTE', 'FAZENDA', 'LUIZ OLIVEIRA'),
('Otavio Almeida Lino de Paula', 'Fazenda Sape', 'LUIZ OLIVEIRA'),
('Caroline Seibt', 'Fazenda Três Pontas', 'LUIZ OLIVEIRA'),
('Edvaldo Prudente', 'Fazenda Joinha', 'LUIZ OLIVEIRA'),
('Ari Ferreira', 'Fazenda Bebedouro', 'LUIZ OLIVEIRA'),
('Silmar Geraldo Martins', 'Fazenda Batatal', 'LUIZ OLIVEIRA'),
('Maria Neusa dos Santos', 'Fazenda Colonia Agrícola', 'LUIZ OLIVEIRA'),
('Gilson Pereira Cardoso', 'Fazenda Alagoas', 'LUIZ OLIVEIRA'),
('Adailto de Freitas Machado', 'Fazenda Morro Feio', 'LUIZ OLIVEIRA'),
('Edgar Moreira Guimarães', 'Aliança Agropecuária', 'LUIZ OLIVEIRA'),
('Valter Jose de Santana', 'Fazenda Conquista', 'LUIZ OLIVEIRA'),
('Daniel André da Silva', 'Fazenda Bravinhos', 'LUIZ OLIVEIRA'),
('Luiz Henrique Resende de Azevedo', 'Fazenda São Bartolomeu', 'LUIZ OLIVEIRA'),
('José Eduardo Menezes', 'Fazenda São Bento', 'LUIZ OLIVEIRA'),
('Libio de Assis Cunha', 'Fazenda Babilônia', 'LUIZ OLIVEIRA'),
('Ilson Jose da Silva', 'Fazenda Serrote', 'LUIZ OLIVEIRA'),
('Cleuton Jose de Araujo', 'Fazenda Pilar', 'LUIZ OLIVEIRA'),
('Roger de Alencar Reis', 'Fazenda Pederneiras', 'LUIZ OLIVEIRA'),
('Eudes Eugenio Simões', 'Sítio Chamomix', 'LUIZ OLIVEIRA'),
('Aurelio Machado Ferreira', 'Fazenda Retiro do Cervo', 'LUIZ OLIVEIRA'),
('Sebastiana Aparecida Ribeiro Gomes', 'Fazenda Santo Antonio', 'LUIZ OLIVEIRA'),
('Ronan Alves Silva', 'Fazenda Primavera', 'LUIZ OLIVEIRA'),
('Keila Cristina Resende', 'Fazenda Campo Redondo', 'LUIZ OLIVEIRA'),
('Carlos Alberto Mendes', 'Fazenda Salitre', 'LUIZ OLIVEIRA'),
('Dimas de Deus Vieira', 'Fazenda Babilonia', 'LUIZ OLIVEIRA'),
('Jaider Shimada Soares', 'Chacara Paraíso', 'LUIZ OLIVEIRA'),
('Oswando Antonio de Almeida', 'Fazenda Pouso Alegre', 'LUIZ OLIVEIRA'),
('Alciro Jose Marques', 'Fazenda Lagoa Formosa', 'LUIZ OLIVEIRA'),
('Celso Antonio Rosa', 'Fazenda Fortaleza', 'LUIZ OLIVEIRA'),
('Silvio Geraldo Martins', 'Fazenda Pasto dos Bois', 'LUIZ OLIVEIRA'),
('Jose Candido Caitano', 'Fazenda Leal', 'LUIZ OLIVEIRA'),
('Eduardo Goncalves de Magalhaes', 'Fazenda Mata Burros', 'LUIZ OLIVEIRA'),
('Agronelli Agroindústria Ltda', 'Fazenda Agronelli', 'LUIZ OLIVEIRA'),
('José Gonçalves de Oliveira', 'Fazenda Lanhosos', 'LUIZ OLIVEIRA'),
('Alexandre Renato Ribeiro', 'Fazenda Campo Redondo', 'LUIZ OLIVEIRA'),
('Dimas Gonzaga', 'Fazenda Boa Vista', 'LUIZ OLIVEIRA'),
('Pedro Paulo de Rezende', 'Fazenda Sertão', 'LUIZ OLIVEIRA'),
('Willian dos Reis Pereira', 'Fazenda Serra Negra', 'LUIZ OLIVEIRA'),
('Ildeu Jose Assunção Rezende', 'Fazenda Antas', 'LUIZ OLIVEIRA'),
('Ilza dos Reis Matos', 'Fazenda Santo Antonio', 'LUIZ OLIVEIRA'),
('Carlos Roberto Braga', 'Fazenda Fortaleza', 'LUIZ OLIVEIRA'),
('Osmar Alves Braga', 'Fazenda Campo do Meio', 'LUIZ OLIVEIRA'),
('Terezinha Moreira Goncalves', 'Fazenda Pitas', 'LUIZ OLIVEIRA'),
('JOSE GONCALVEZ DE OLIVEIRA', 'FAZENDA BARREIRO', 'LUIZ OLIVEIRA'),
('Marco Antonio Duarte Veloso', 'Fazenda Esmeril', 'LUIZ OLIVEIRA'),
('Osanan Pereira Caixeta', 'Fazenda Pedacinho do Céu', 'LUIZ OLIVEIRA'),
('Alexandre João de Lima', 'Fazenda Caixetas', 'LUIZ OLIVEIRA'),
('Arthur Mota Faria', 'Fazenda Alagoas', 'LUIZ OLIVEIRA'),
('Pedro Brandao', 'FAZENDA SOLO SAGRADO', 'LUIZ OLIVEIRA'),
('Bento da Silva', 'Bararuba', 'João Amaral'),
('GUNTHER LOURENZEN', 'FAZENDA UMBU', 'Gunther Lourenzen'),
('Fazenda Demo', 'Fazenda Teste', 'Anderson Schmitt'),
('Matias Gregory', 'Granja Gregory', 'Nacir Penz'),
('JADSON WERNER', 'WERNER', 'Nacir Penz'),
('GIONGO E HAMMEL AGROPECUARIA LTDA GIONGO E HAMMEL', 'GIONGO E HAMMEL', 'Nacir Penz'),
('DEMO', 'Treinamento 27 05 2024', 'JOSE BICALHO'),
('Fazenda FINI', 'Fazenda FINI', 'Diogo Penz'),
('Alex Sandro da Rosa', 'Alex da Rosa', 'Diogo Penz'),
('Ari Busanello', 'Granja Busanello', 'Diogo Penz'),
('Giongo &amp', '', 'Diogo Penz'),
('demonstrativa', 'faz demonstrativa', 'Rafaela Marin'),
('MARCOS MARCOLIN', 'FAZENDA MARCOLIN', 'Rafaela Marin'),
('AIRTON SALVADOR', 'TAMBO SALVADOR', 'Rafaela Marin'),
('JONATAN BAGGIO', 'GRANJA BAGGIO', 'Rafaela Marin'),
('MAIARA E GILBERTO LODI', 'GRANJA LODI', 'Rafaela Marin'),
('TIAGO E BRUNA SEGALIN', 'GRANJA CAÇADOR', 'Rafaela Marin'),
('GESSICA E ANDERSON BOLSONI', 'TAMBO BOLSONI', 'Rafaela Marin'),
('ELOI POMATTI', 'POMATTI', 'Rafaela Marin'),
('ARTHUR SALVADOR', 'ARTHUR SALVADOR', 'Rafaela Marin'),
('ROSANE SCALABRIN LERIN', 'ROSANE SCALABRIN LERIN', 'Rafaela Marin'),
('LUCAS MAROSO', 'GRANJA MAROSO', 'Rafaela Marin'),
('JUAREZ E MORGANA PRESSI', 'FAZENDA PRESSI', 'Rafaela Marin'),
('ELIAS SPADA', 'ELIAS SPADA', 'Rafaela Marin'),
('ARTUR ZIGLIOLI', 'ARTUR ZIGLIOLI', 'Rafaela Marin'),
('ADILSON LUNARDI', 'ADILSON LUNARDI', 'Rafaela Marin'),
('Demonstrativo', 'Fazenda Demonstrativa', 'Danielly Broleze'),
('Paulo Dias de Sousa', 'Fazenda Alagoas', 'Danielly Broleze'),
('Deleni Caixeta Silva', 'Fazenda São Luiz', 'Danielly Broleze'),
('Milton Francisco de oliveira', 'Fazenda Paraíso', 'Danielly Broleze'),
('Carlos Bruno de Castro', 'Fazenda Alagoas', 'Danielly Broleze'),
('Alicio Donizetti da Silva', 'Fazenda São Luiz', 'Danielly Broleze'),
('Cleuton José de Araujo', 'Fazenda Pilar', 'Danielly Broleze'),
('Alencar Francisco Pereira', 'Fazenda Alagoas', 'Danielly Broleze'),
('Fernando José Rosa', 'Fazenda lagoa Formosa', 'Danielly Broleze'),
('Antonio Pereira de Castro', 'Fazenda Alagoas', 'Danielly Broleze'),
('demo', 'demontraçao', 'Felipe tavares'),
('Alexandre Vinícius Costa Soares', 'Fazenda Bonsucesso', 'Felipe tavares'),
('Marcos José de Souza', 'do queijo', 'Felipe tavares'),
('MAGNA MARIA DE SOUSA', 'Fazenda Aurora', 'Felipe tavares'),
('VITOR PENIDO', 'FAZENDA PONTE ALTA PAU DO MONJOLO', 'Felipe tavares'),
('POLIDORO JOAQUIM DE FARIA', 'FAZENDA AGUA PARADA, SN', 'Felipe tavares'),
('DEMO', 'FAZENDA DEMONSTRATIVA', 'Brendo'),
('FAZENDA DEMO', 'DEMO', 'Daniel lenhardt'),
('FRITZ WEHEBRIK', 'FAZENDA FRITZ', 'Daniel lenhardt'),
('CLAUDIO POSSA', 'FAZENDA POSSA', 'Daniel lenhardt'),
('FABIO LAZARETTI', 'FABIO MUILLER', 'Daniel lenhardt'),
('FAZ MALAGUTTI', 'FAZ MALAGUTTI', 'Daniel lenhardt'),
('ANTONIO AUGUSTO SANTIN', 'FAZENDA SANTIN', 'Daniel lenhardt'),
('ANGELA CRISTINA TRINDADE', 'FANZENDA TRINDADE', 'Daniel lenhardt'),
('VILSON TAFFAREL', 'FAZENDA ALTO DA SERRA', 'Daniel lenhardt'),
('GIOVANE ROSSETTO', 'FAZ ROSSETTO', 'Daniel lenhardt'),
('GUSTAVO MARCON DALLPIVA', 'GUSTAVO MARCON DALLPIVA', 'Daniel lenhardt'),
('Fazenda Ibira', 'Fazenda Demo Ibira', 'Diego Lima'),
('Fazenda Casagrande', 'Fazenda Casagrande', 'Daniel Casagrande'),
('FAZENDA DEMO', 'fazenda demo', 'Nayra'),
('DEMO', 'FAZENDA', 'Nayra'),
('EUDES EUGENIO SIMÕES', 'FAZENDA CHAMONIX', 'Nayra'),
('PEDRO PAULO DE REZENDE', 'FAZENDA SERTAO, SN', 'Nayra'),
('ILDEU JOSE ASSUNÇÃO', 'FAZENDA ESTREITO', 'Nayra'),
('SEBASTIANA APARECIDA RIBEIRO GOMES', 'FAZENDA SANTO ANTONIO, SN', 'Nayra'),
('fazenda demo', 'fazenda demo', 'Denilson Augusto'),
('FAZENDA DEMO', 'FAZENDA DEMONSTRATIVA', 'Alessandro'),
('edison', 'grahl', 'Edison'),
('FAZENDA DEMO 1', 'DEMONSTRATIVO', 'Douglas'),
('Agropecuária Arapari', 'Agropecuária Arapari', 'Douglas'),
('Gediel Griebeler', 'GEDIEL', 'Douglas'),
('Gabrieli Putton', 'Gabrieli Putton', 'Douglas'),
('Jorge Afonso Stoeckl', 'Jorge Afonso Stoeckl', 'Douglas'),
('EXEMPLO', 'FAZENDA EXEMPLO', 'Rhayna'),
('MARLENE KAIUT', 'RAINHA DO JERSEY', 'Rhayna'),
('LUIZ GUSTAVO ALAIKO STECKEIN', 'FAZENDA POTREIRO', 'Rhayna'),
('DENISE TAQUES RICKLI', 'FAZENDA BELA VISTA', 'Rhayna'),
('EMÍLIO JANSSEN', 'CHÁCARA DE NIELT', 'Rhayna'),
('TREINAMENTO PARANÁ', 'TREINAMENTO PARANÁ', 'Rhayna'),
('GISELI MOTTIM', 'FAZENDA ENTRE RIOS', 'Rhayna'),
('futuro genetica', 'fazenda demonstrativa', 'Nilmar Tagliari'),
('LORENZETT', 'FAZENDA LORENZETT', 'Nilmar Tagliari'),
('GIOLVANI KRENCHINSKI', 'KRENCHINSKI', 'Nilmar Tagliari'),
('MARCIONE MARCOS MEURER', 'ESTANCIA CAROLINE', 'Nilmar Tagliari'),
('Paulo Henrique de Sousa Tavares', 'Fazenda Tavares', 'Paulo Henrique de Sousa Tavares'),
('Lucas cruz', 'São Roque', 'Lucas Almeida Cruz'),
('CELSO ALEXANDRE BIAGIO', 'campo limpo', 'Celso Alexandre Biagio'),
('Treino', 'Treino', 'Iago Macaris'),
('MARCIO MASSARO', 'MARCIO MASSARO', 'Iago Macaris'),
('DENISE RODRIGUES VALLE FAYAD', 'DENISE RODRIGUES VALLE FAYAD', 'Iago Macaris'),
('Demo', 'Demo', 'Gilberto Berringer de Assumpção'),
('Rildo Oliveira', 'Fazenda Serra do Salitre', 'Ricardo Mansilha'),
('Humberto Chaves Orlandi', 'x', 'Ricardo Mansilha'),
('HUMBERTO ORLANDI', 'Fazenda Santa Marta', 'Ricardo Mansilha'),
('Carlos Baudraz', 'j', 'Ricardo Mansilha'),
('Bernardo Araujo Jorge', 'Fazenda Germina', 'Ricardo Mansilha'),
('Lucio Drinko', 'Drink', 'Ricardo Mansilha'),
('POLACO', 'SITIO LINDA PAISAGEM', 'Ricardo Mansilha'),
('FLAVIANO', 'FLAVIANO', 'Ricardo Mansilha'),
('JULIO CESAR MARTINS GALACHE', 'CHACARA RESSACA', 'Ricardo Mansilha'),
('MATILDE ARAUJO AMARAL GUIMARÃES', 'FAZENDA SANTA CRUZ', 'Ricardo Mansilha'),
('MARINA INATIVO', 'FAZENDA SANTA CRUZ', 'Ricardo Mansilha'),
('ROBSON YURKOSKI', 'LEITERIA YURKOSKI', 'Ricardo Mansilha'),
('Antonio Gilberto da Silva Jr', 'Fazenda', 'Ricardo Mansilha'),
('Nico Biersteker', 'Fazenda Lagoa Dourada', 'Caio Godoi'),
('MATEUS GOLDMEIIER', 'FAZENDA GOLDMEIER', 'Josnei Nardi');

-- Criar vínculos que ainda não existem
INSERT INTO public.user_farms (user_id, farm_id, role)
SELECT DISTINCT
  p.id as user_id,
  f.id as farm_id,
  'technician'::farm_role as role
FROM temp_all_technician_links t
JOIN public.profiles p ON LOWER(p.full_name) LIKE '%' || LOWER(t.technician_name) || '%'
JOIN public.farms f ON (
  LOWER(f.name) LIKE '%' || LOWER(t.farm_name) || '%'
  OR LOWER(f.owner_name) LIKE '%' || LOWER(t.owner_name) || '%'
)
WHERE NOT EXISTS (
  SELECT 1 FROM public.user_farms uf
  WHERE uf.user_id = p.id AND uf.farm_id = f.id
)
AND t.farm_name != ''; -- Ignorar linhas com farm_name vazio

DROP TABLE temp_all_technician_links;
