-- Corrigir a view bulls_denorm para expandir as PTAs do JSON
DROP VIEW IF EXISTS public.bulls_denorm;

CREATE VIEW public.bulls_denorm AS
SELECT 
    b.id,
    b.code,
    b.name,
    b.registration,
    b.birth_date,
    b.company,
    b.sire_naab,
    b.mgs_naab,
    b.mmgs_naab,
    b.created_at,
    b.updated_at,
    -- Expandir PTAs do JSON em colunas individuais
    (b.ptas->>'hhp_dollar')::numeric as hhp_dollar,
    (b.ptas->>'tpi')::numeric as tpi,
    (b.ptas->>'nm_dollar')::numeric as nm_dollar,
    (b.ptas->>'cm_dollar')::numeric as cm_dollar,
    (b.ptas->>'fm_dollar')::numeric as fm_dollar,
    (b.ptas->>'gm_dollar')::numeric as gm_dollar,
    (b.ptas->>'f_sav')::numeric as f_sav,
    (b.ptas->>'ptam')::numeric as ptam,
    (b.ptas->>'cfp')::numeric as cfp,
    (b.ptas->>'ptaf')::numeric as ptaf,
    (b.ptas->>'ptaf_pct')::numeric as ptaf_pct,
    (b.ptas->>'ptap')::numeric as ptap,
    (b.ptas->>'ptap_pct')::numeric as ptap_pct,
    (b.ptas->>'pl')::numeric as pl,
    (b.ptas->>'dpr')::numeric as dpr,
    (b.ptas->>'liv')::numeric as liv,
    (b.ptas->>'scs')::numeric as scs,
    (b.ptas->>'mast')::numeric as mast,
    (b.ptas->>'met')::numeric as met,
    (b.ptas->>'rp')::numeric as rp,
    (b.ptas->>'da')::numeric as da,
    (b.ptas->>'ket')::numeric as ket,
    (b.ptas->>'mf')::numeric as mf,
    (b.ptas->>'ptat')::numeric as ptat,
    (b.ptas->>'udc')::numeric as udc,
    (b.ptas->>'flc')::numeric as flc,
    (b.ptas->>'sce')::numeric as sce,
    (b.ptas->>'dce')::numeric as dce,
    (b.ptas->>'ssb')::numeric as ssb,
    (b.ptas->>'dsb')::numeric as dsb,
    (b.ptas->>'h_liv')::numeric as h_liv,
    (b.ptas->>'ccr')::numeric as ccr,
    (b.ptas->>'hcr')::numeric as hcr,
    (b.ptas->>'fi')::numeric as fi,
    (b.ptas->>'gl')::numeric as gl,
    (b.ptas->>'efc')::numeric as efc,
    (b.ptas->>'bwc')::numeric as bwc,
    (b.ptas->>'sta')::numeric as sta,
    (b.ptas->>'str')::numeric as str,
    (b.ptas->>'dfm')::numeric as dfm,
    (b.ptas->>'rua')::numeric as rua,
    (b.ptas->>'rls')::numeric as rls,
    (b.ptas->>'rtp')::numeric as rtp,
    (b.ptas->>'ftl')::numeric as ftl,
    (b.ptas->>'rw')::numeric as rw,
    (b.ptas->>'rlr')::numeric as rlr,
    (b.ptas->>'fta')::numeric as fta,
    (b.ptas->>'fls')::numeric as fls,
    (b.ptas->>'fua')::numeric as fua,
    (b.ptas->>'ruh')::numeric as ruh,
    (b.ptas->>'ruw')::numeric as ruw,
    (b.ptas->>'ucl')::numeric as ucl,
    (b.ptas->>'udp')::numeric as udp,
    (b.ptas->>'ftp')::numeric as ftp,
    (b.ptas->>'rfi')::numeric as rfi,
    b.ptas->>'beta_casein' as beta_casein,
    b.ptas->>'kappa_casein' as kappa_casein,
    (b.ptas->>'gfi')::numeric as gfi
FROM public.bulls b;