-- Add missing columns to bulls table
ALTER TABLE public.bulls 
ADD COLUMN IF NOT EXISTS registration text,
ADD COLUMN IF NOT EXISTS pedigree text,
ADD COLUMN IF NOT EXISTS hhp_dollar numeric,
ADD COLUMN IF NOT EXISTS tpi numeric,
ADD COLUMN IF NOT EXISTS nm_dollar numeric,
ADD COLUMN IF NOT EXISTS cm_dollar numeric,
ADD COLUMN IF NOT EXISTS fm_dollar numeric,
ADD COLUMN IF NOT EXISTS gm_dollar numeric,
ADD COLUMN IF NOT EXISTS f_sav numeric,
ADD COLUMN IF NOT EXISTS ptam numeric,
ADD COLUMN IF NOT EXISTS cfp numeric,
ADD COLUMN IF NOT EXISTS ptaf numeric,
ADD COLUMN IF NOT EXISTS ptaf_pct numeric,
ADD COLUMN IF NOT EXISTS ptap numeric,
ADD COLUMN IF NOT EXISTS ptap_pct numeric,
ADD COLUMN IF NOT EXISTS pl numeric,
ADD COLUMN IF NOT EXISTS dpr numeric,
ADD COLUMN IF NOT EXISTS liv numeric,
ADD COLUMN IF NOT EXISTS scs numeric,
ADD COLUMN IF NOT EXISTS mast numeric,
ADD COLUMN IF NOT EXISTS met numeric,
ADD COLUMN IF NOT EXISTS rp numeric,
ADD COLUMN IF NOT EXISTS da numeric,
ADD COLUMN IF NOT EXISTS ket numeric,
ADD COLUMN IF NOT EXISTS mf numeric,
ADD COLUMN IF NOT EXISTS ptat numeric,
ADD COLUMN IF NOT EXISTS udc numeric,
ADD COLUMN IF NOT EXISTS flc numeric,
ADD COLUMN IF NOT EXISTS sce numeric,
ADD COLUMN IF NOT EXISTS dce numeric,
ADD COLUMN IF NOT EXISTS ssb numeric,
ADD COLUMN IF NOT EXISTS dsb numeric,
ADD COLUMN IF NOT EXISTS h_liv numeric,
ADD COLUMN IF NOT EXISTS ccr numeric,
ADD COLUMN IF NOT EXISTS hcr numeric,
ADD COLUMN IF NOT EXISTS fi numeric,
ADD COLUMN IF NOT EXISTS gl numeric,
ADD COLUMN IF NOT EXISTS efc numeric,
ADD COLUMN IF NOT EXISTS bwc numeric,
ADD COLUMN IF NOT EXISTS sta numeric,
ADD COLUMN IF NOT EXISTS str numeric,
ADD COLUMN IF NOT EXISTS dfm numeric,
ADD COLUMN IF NOT EXISTS rua numeric,
ADD COLUMN IF NOT EXISTS rls numeric,
ADD COLUMN IF NOT EXISTS rtp numeric,
ADD COLUMN IF NOT EXISTS ftl numeric,
ADD COLUMN IF NOT EXISTS rw numeric,
ADD COLUMN IF NOT EXISTS rlr numeric,
ADD COLUMN IF NOT EXISTS fta numeric,
ADD COLUMN IF NOT EXISTS fls numeric,
ADD COLUMN IF NOT EXISTS fua numeric,
ADD COLUMN IF NOT EXISTS ruh numeric,
ADD COLUMN IF NOT EXISTS ruw numeric,
ADD COLUMN IF NOT EXISTS ucl numeric,
ADD COLUMN IF NOT EXISTS udp numeric,
ADD COLUMN IF NOT EXISTS ftp numeric,
ADD COLUMN IF NOT EXISTS rfi numeric,
ADD COLUMN IF NOT EXISTS beta_casein text,
ADD COLUMN IF NOT EXISTS kappa_casein text,
ADD COLUMN IF NOT EXISTS gfi numeric;

-- Recreate bulls_denorm view with all columns
DROP VIEW IF EXISTS public.bulls_denorm;

CREATE VIEW public.bulls_denorm AS
SELECT 
    b.id,
    b.code,
    b.name,
    b.registration,
    b.pedigree,
    b.birth_date,
    b.company,
    b.sire_naab,
    b.mgs_naab,
    b.mmgs_naab,
    b.created_at,
    b.updated_at,
    -- Economic indices
    b.hhp_dollar,
    b.tpi,
    b.nm_dollar,
    b.cm_dollar,
    b.fm_dollar,
    b.gm_dollar,
    -- Production traits
    b.f_sav,
    b.ptam,
    b.cfp,
    b.ptaf,
    b.ptaf_pct,
    b.ptap,
    b.ptap_pct,
    b.pl,
    -- Health traits
    b.dpr,
    b.liv,
    b.scs,
    b.mast,
    b.met,
    b.rp,
    b.da,
    b.ket,
    b.mf,
    -- Conformation traits
    b.ptat,
    b.udc,
    b.flc,
    b.sce,
    b.dce,
    b.ssb,
    b.dsb,
    b.h_liv,
    b.ccr,
    b.hcr,
    b.fi,
    b.gl,
    b.efc,
    b.bwc,
    b.sta,
    b.str,
    b.dfm,
    b.rua,
    b.rls,
    b.rtp,
    b.ftl,
    b.rw,
    b.rlr,
    b.fta,
    b.fls,
    b.fua,
    b.ruh,
    b.ruw,
    b.ucl,
    b.udp,
    b.ftp,
    b.rfi,
    -- Casein variants
    b.beta_casein,
    b.kappa_casein,
    -- Additional traits
    b.gfi
FROM public.bulls b;