
-- View bulls_denorm: aliases for backward compatibility with codebase
CREATE OR REPLACE VIEW public.bulls_denorm AS
SELECT
  id,
  naab_code AS code,
  name,
  registration,
  birth_date,
  sire_naab,
  mgs_naab,
  mmgs_naab,
  company,
  hhp_dollar,
  tpi,
  nm_dollar,
  cm_dollar,
  fm_dollar,
  gm_dollar,
  f_sav,
  pta_milk AS ptam,
  cfp,
  pta_fat AS ptaf,
  pta_fat_pct AS ptaf_pct,
  pta_protein AS ptap,
  pta_protein_pct AS ptap_pct,
  pta_pl AS pl,
  pta_dpr AS dpr,
  pta_livability AS liv,
  pta_scs AS scs,
  mast,
  met,
  rp,
  da,
  ket,
  mf_num AS mf,
  pta_ptat AS ptat,
  pta_udc AS udc,
  pta_flc AS flc,
  pta_sce AS sce,
  pta_sire_sce AS dce,
  ssb,
  dsb,
  h_liv,
  ccr_num AS ccr,
  hcr_num AS hcr,
  fi,
  bwc,
  sta,
  str_num AS str,
  dfm,
  rua,
  rls,
  rtp,
  ftl,
  rw,
  rlr,
  fta,
  fls,
  fua,
  ruh,
  ruw,
  ucl,
  udp,
  ftp,
  rfi,
  beta_casein,
  kappa_casein,
  gfi
FROM public.bulls;

-- View females_denorm: aliases for backward compatibility with codebase
CREATE OR REPLACE VIEW public.females_denorm AS
SELECT
  id,
  client_id AS farm_id,
  client_id,
  name,
  identifier,
  ear_tag,
  cdcb_id,
  registration,
  birth_date,
  breed,
  category,
  status,
  parity_order,
  fonte,
  sire_naab,
  mgs_naab,
  mmgs_naab,
  hhp_dollar,
  tpi,
  nm_dollar,
  cm_dollar,
  fm_dollar,
  gm_dollar,
  f_sav,
  pta_milk AS ptam,
  cfp,
  pta_fat AS ptaf,
  pta_fat_pct AS ptaf_pct,
  pta_protein AS ptap,
  pta_protein_pct AS ptap_pct,
  pta_pl AS pl,
  pta_dpr AS dpr,
  pta_livability AS liv,
  pta_scs AS scs,
  mast,
  met,
  rp,
  da,
  ket,
  mf_num AS mf,
  pta_ptat AS ptat,
  pta_udc AS udc,
  pta_flc AS flc,
  pta_sce AS sce,
  pta_sire_sce AS dce,
  ssb,
  dsb,
  h_liv,
  pta_ccr AS ccr,
  pta_hcr AS hcr,
  fi,
  gl,
  efc,
  bwc,
  sta,
  str_num AS str,
  dfm,
  rua,
  rls,
  rtp,
  ftl,
  rw,
  rlr,
  fta,
  fls,
  fua,
  ruh,
  ruw,
  ucl,
  udp,
  ftp,
  rfi,
  beta_casein,
  kappa_casein,
  gfi,
  nmpf,
  cheese_merit,
  fluid_merit,
  grazing_merit,
  genomic_result_id,
  created_at,
  updated_at,
  deleted_at,
  ptas
FROM public.females;

-- Also add the get_bull_by_naab and search_bulls RPC functions that the code uses
CREATE OR REPLACE FUNCTION public.get_bull_by_naab(naab text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  result jsonb;
  bull_record record;
BEGIN
  SELECT * INTO bull_record
  FROM bulls_denorm
  WHERE code IS NOT NULL
    AND UPPER(REPLACE(REPLACE(REPLACE(code, ' ', ''), '-', ''), '.', ''))
      = UPPER(REPLACE(REPLACE(REPLACE(naab, ' ', ''), '-', ''), '.', ''))
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('found', false);
  END IF;

  RETURN jsonb_build_object(
    'found', true,
    'bull_id', bull_record.id,
    'code', bull_record.code,
    'name', bull_record.name,
    'registration', bull_record.registration,
    'birth_date', bull_record.birth_date,
    'sire_naab', bull_record.sire_naab,
    'mgs_naab', bull_record.mgs_naab,
    'mmgs_naab', bull_record.mmgs_naab,
    'company', bull_record.company,
    'hhp_dollar', bull_record.hhp_dollar,
    'tpi', bull_record.tpi,
    'nm_dollar', bull_record.nm_dollar,
    'cm_dollar', bull_record.cm_dollar,
    'fm_dollar', bull_record.fm_dollar,
    'gm_dollar', bull_record.gm_dollar,
    'f_sav', bull_record.f_sav,
    'ptam', bull_record.ptam,
    'cfp', bull_record.cfp,
    'ptaf', bull_record.ptaf,
    'ptaf_pct', bull_record.ptaf_pct,
    'ptap', bull_record.ptap,
    'ptap_pct', bull_record.ptap_pct,
    'pl', bull_record.pl,
    'dpr', bull_record.dpr,
    'liv', bull_record.liv,
    'scs', bull_record.scs,
    'mast', bull_record.mast,
    'met', bull_record.met,
    'rp', bull_record.rp,
    'da', bull_record.da,
    'ket', bull_record.ket,
    'mf', bull_record.mf,
    'ptat', bull_record.ptat,
    'udc', bull_record.udc,
    'flc', bull_record.flc,
    'sce', bull_record.sce,
    'dce', bull_record.dce,
    'ssb', bull_record.ssb,
    'dsb', bull_record.dsb,
    'h_liv', bull_record.h_liv,
    'ccr', bull_record.ccr,
    'hcr', bull_record.hcr,
    'fi', bull_record.fi,
    'bwc', bull_record.bwc,
    'sta', bull_record.sta,
    'str', bull_record.str,
    'dfm', bull_record.dfm,
    'rua', bull_record.rua,
    'rls', bull_record.rls,
    'rtp', bull_record.rtp,
    'ftl', bull_record.ftl,
    'rw', bull_record.rw,
    'rlr', bull_record.rlr,
    'fta', bull_record.fta,
    'fls', bull_record.fls,
    'fua', bull_record.fua,
    'ruh', bull_record.ruh,
    'ruw', bull_record.ruw,
    'ucl', bull_record.ucl,
    'udp', bull_record.udp,
    'ftp', bull_record.ftp,
    'rfi', bull_record.rfi,
    'beta_casein', bull_record.beta_casein,
    'kappa_casein', bull_record.kappa_casein,
    'gfi', bull_record.gfi
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.search_bulls(q text, limit_count int DEFAULT 10)
RETURNS SETOF jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT jsonb_build_object(
    'bull_id', b.id,
    'code', b.code,
    'name', b.name,
    'registration', b.registration,
    'birth_date', b.birth_date,
    'sire_naab', b.sire_naab,
    'mgs_naab', b.mgs_naab,
    'mmgs_naab', b.mmgs_naab,
    'company', b.company,
    'hhp_dollar', b.hhp_dollar,
    'tpi', b.tpi,
    'nm_dollar', b.nm_dollar,
    'cm_dollar', b.cm_dollar,
    'fm_dollar', b.fm_dollar,
    'gm_dollar', b.gm_dollar,
    'f_sav', b.f_sav,
    'ptam', b.ptam,
    'cfp', b.cfp,
    'ptaf', b.ptaf,
    'ptaf_pct', b.ptaf_pct,
    'ptap', b.ptap,
    'ptap_pct', b.ptap_pct,
    'pl', b.pl,
    'dpr', b.dpr,
    'liv', b.liv,
    'scs', b.scs,
    'mast', b.mast,
    'met', b.met,
    'rp', b.rp,
    'da', b.da,
    'ket', b.ket,
    'mf', b.mf,
    'ptat', b.ptat,
    'udc', b.udc,
    'flc', b.flc,
    'sce', b.sce,
    'dce', b.dce,
    'ssb', b.ssb,
    'dsb', b.dsb,
    'h_liv', b.h_liv,
    'ccr', b.ccr,
    'hcr', b.hcr,
    'fi', b.fi,
    'bwc', b.bwc,
    'sta', b.sta,
    'str', b.str,
    'dfm', b.dfm,
    'rua', b.rua,
    'rls', b.rls,
    'rtp', b.rtp,
    'ftl', b.ftl,
    'rw', b.rw,
    'rlr', b.rlr,
    'fta', b.fta,
    'fls', b.fls,
    'fua', b.fua,
    'ruh', b.ruh,
    'ruw', b.ruw,
    'ucl', b.ucl,
    'udp', b.udp,
    'ftp', b.ftp,
    'rfi', b.rfi,
    'beta_casein', b.beta_casein,
    'kappa_casein', b.kappa_casein,
    'gfi', b.gfi
  )
  FROM bulls_denorm b
  WHERE
    b.code ILIKE '%' || q || '%'
    OR b.name ILIKE '%' || q || '%'
    OR b.registration ILIKE '%' || q || '%'
  LIMIT limit_count;
END;
$$;
